anchor_version = "0.24.2"

[workspace]
members = [
    "common",
    "mango-macro",
    "program",
    "mango-logs"
]

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
mango = "FcfzrnurPFXwxbx332wScnD5P86DwhpLpBbQsnr6LcH5"

[programs.devnet]
mango = "FcfzrnurPFXwxbx332wScnD5P86DwhpLpBbQsnr6LcH5"
